# Classifiers
KNN = 1
GBC = 2
SVM = 3

# Methods
VOTING = 0
STD_CV = 1
LOO = 2

# Solution volume
SOLV_MODEL = 1
SOLUD_MODEL = 2
NO_MODEL = 0

FEAT_VALUES_IMPORTANCE = 'feats_importance_values'
FEAT_NAMES_IMPORTANCE = 'feats_names_by_importance'

# Dictionary from inchi key to its chemical name
INCHI_TO_CHEMNAME = {'null': 'null',
                     'YEJRWHAVMIAJKC-UHFFFAOYSA-N': 'Gamma-Butyrolactone',
                     'IAZDPXIOMUYVGZ-UHFFFAOYSA-N': 'Dimethyl sulfoxide',
                     'BDAGIHXWWSANSR-UHFFFAOYSA-N': 'Formic Acid',
                     'RQQRAHKHDFPBMC-UHFFFAOYSA-L': 'Lead Diiodide',
                     'XFYICZOIWSBQSK-UHFFFAOYSA-N': 'Ethylammonium Iodide',
                     'LLWRXQXPJMPHLR-UHFFFAOYSA-N': 'Methylammonium iodide',
                     'UPHCENSIMPJEIS-UHFFFAOYSA-N': 'Phenethylammonium iodide',
                     'GGYGJCFIYJVWIP-UHFFFAOYSA-N': 'Acetamidinium iodide',
                     'CALQKRVFTWDYDG-UHFFFAOYSA-N': 'n-Butylammonium iodide',
                     'UUDRLGYROXTISK-UHFFFAOYSA-N': 'Guanidinium iodide',
                     'YMWUJEATGCHHMB-UHFFFAOYSA-N': 'Dichloromethane',
                     'JMXLWMIFDJCGBV-UHFFFAOYSA-N': 'Dimethylammonium iodide',
                     'KFQARYBEAKAXIC-UHFFFAOYSA-N': 'Phenylammonium Iodide',
                     'NLJDBTZLVTWXRG-UHFFFAOYSA-N': 't-Butylammonium Iodide',
                     'GIAPQOZCVIEHNY-UHFFFAOYSA-N': 'N-propylammonium Iodide',
                     'QHJPGANWSLEMTI-UHFFFAOYSA-N': 'Formamidinium Iodide',
                     'WXTNTIQDYHIFEG-UHFFFAOYSA-N': '1,4-Diazabicyclo[2,2,2]octane-1,4-diium Iodide',
                     'LCTUISCIGMWMAT-UHFFFAOYSA-N': '4-Fluoro-Benzylammonium iodide',
                     'NOHLSFNWSBZSBW-UHFFFAOYSA-N': '4-Fluoro-Phenethylammonium iodide',
                     'FJFIJIDZQADKEE-UHFFFAOYSA-N': '4-Fluoro-Phenylammonium iodide',
                     'QRFXELVDJSDWHX-UHFFFAOYSA-N': '4-Methoxy-Phenylammonium iodide',
                     'SQXJHWOXNLTOOO-UHFFFAOYSA-N': '4-Trifluoromethyl-Benzylammonium iodide',
                     'KOAGKPNEVYEZDU-UHFFFAOYSA-N': '4-Trifluoromethyl-Phenylammonium iodide',
                     'MVPPADPHJFYWMZ-UHFFFAOYSA-N': 'chlorobenzene',
                     'CWJKVUQGXKYWTR-UHFFFAOYSA-N': 'Acetamidinium bromide',
                     'QJFMCHRSDOLMHA-UHFFFAOYSA-N': 'Benzylammonium Bromide',
                     'PPCHYMCMRUGLHR-UHFFFAOYSA-N': 'Benzylammonium Iodide',
                     'XAKAQFUGWUAPJN-UHFFFAOYSA-N': 'Beta Alanine Hydroiodide',
                     'KOECRLKKXSXCPB-UHFFFAOYSA-K': 'Bismuth iodide',
                     'XQPRBTXUXXVTKB-UHFFFAOYSA-M': 'Cesium iodide',
                     'ZMXDDKWLCZADIW-UHFFFAOYSA-N': 'Dimethylformamide',
                     'BCQZYUOYVLJOPE-UHFFFAOYSA-N': 'Ethane-1,2-diammonium bromide',
                     'IWNWLPUNKAYUAW-UHFFFAOYSA-N': 'Ethane-1,2-diammonium iodide',
                     'PNZDZRMOBIIQTC-UHFFFAOYSA-N': 'Ethylammonium bromide',
                     'QWANGZFTSGZRPZ-UHFFFAOYSA-N': 'Formamidinium bromide',
                     'VQNVZLDDLJBKNS-UHFFFAOYSA-N': 'Guanidinium bromide',
                     'VMLAEGAAHIIWJX-UHFFFAOYSA-N': 'i-Propylammonium iodide',
                     'JBOIAZWJIACNJF-UHFFFAOYSA-N': 'Imidazolium Iodide',
                     'RFYSBVUZWGEPBE-UHFFFAOYSA-N': 'iso-Butylammonium bromide',
                     'FCTHQYIDLRRROX-UHFFFAOYSA-N': 'iso-Butylammonium iodide',
                     'UZHWWTHDRVLCJU-UHFFFAOYSA-N': 'iso-Pentylammonium iodide',
                     'MCEUZMYFCCOOQO-UHFFFAOYSA-L': 'Lead(II) acetate trihydrate',
                     'ZASWJUOMEGBQCQ-UHFFFAOYSA-L': 'Lead(II) bromide',
                     'ISWNAMNOYHCTSB-UHFFFAOYSA-N': 'Methylammonium bromide',
                     'VAWHFUNJDMQUSB-UHFFFAOYSA-N': 'Morpholinium Iodide',
                     'VZXFEELLBDNLAL-UHFFFAOYSA-N': 'n-Dodecylammonium bromide',
                     'PXWSKGXEHZHFJA-UHFFFAOYSA-N': 'n-Dodecylammonium iodide',
                     'VNAAUNTYIONOHR-UHFFFAOYSA-N': 'n-Hexylammonium iodide',
                     'HBZSVMFYMAOGRS-UHFFFAOYSA-N': 'n-Octylammonium Iodide',
                     'FEUPHURYMJEUIH-UHFFFAOYSA-N': 'neo-Pentylammonium bromide',
                     'CQWGDVVCKBJLNX-UHFFFAOYSA-N': 'neo-Pentylammonium iodide',
                     'IRAGENYJMTVCCV-UHFFFAOYSA-N': 'Phenethylammonium bromide',
                     'UXWKNNJFYZFNDI-UHFFFAOYSA-N': 'piperazine dihydrobromide',
                     'QZCGFUVVXNFSLE-UHFFFAOYSA-N': 'Piperazine-1,4-diium iodide',
                     'HBPSMMXRESDUSG-UHFFFAOYSA-N': 'Piperidinium Iodide',
                     'IMROMDMJAWUWLK-UHFFFAOYSA-N': 'Poly(vinyl alcohol), Mw89000-98000, >99% hydrolyzed)',
                     'QNBVYCDYFJUNLO-UHDJGPCESA-N': 'Pralidoxime iodide',
                     'UMDDLGMCNFAZDX-UHFFFAOYSA-O': 'Propane-1,3-diammonium iodide',
                     'VFDOIPKMSSDMCV-UHFFFAOYSA-N': 'Pyrrolidinium Bromide',
                     'DMFMZFFIQRMJQZ-UHFFFAOYSA-N': 'Pyrrolidinium Iodide',
                     'DYEHDACATJUKSZ-UHFFFAOYSA-N': 'Quinuclidin-1-ium bromide',
                     'LYHPZBKXSHVBDW-UHFFFAOYSA-N': 'Quinuclidin-1-ium iodide',
                     'UXYJHTKQEFCXBJ-UHFFFAOYSA-N': 'tert-Octylammonium iodide',
                     'BJDYCCHRZIFCGN-UHFFFAOYSA-N': 'Pyridinium Iodide',
                     'ZEVRFFCPALTVDN-UHFFFAOYSA-N': 'Cyclohexylmethylammonium iodide',
                     'WGYRINYTHSORGH-UHFFFAOYSA-N': 'Cyclohexylammonium iodide',
                     'XZUCBFLUEBDNSJ-UHFFFAOYSA-N': 'Butane-1,4-diammonium Iodide',
                     'RYYSZNVPBLKLRS-UHFFFAOYSA-N': '1,4-Benzene diammonium iodide',
                     'DWOWCUCDJIERQX-UHFFFAOYSA-M': '5-Azaspiro[4.4]nonan-5-ium iodide',
                     'YYMLRIWBISZOMT-UHFFFAOYSA-N': 'Diethylammonium iodide',
                     'UVLZLKCGKYLKOR-UHFFFAOYSA-N': '2-Pyrrolidin-1-ium-1-ylethylammonium iodide',
                     'BAMDIFIROXTEEM-UHFFFAOYSA-N': 'N,N-Dimethylethane- 1,2-diammonium iodide',
                     'JERSPYRKVMAEJY-UHFFFAOYSA-N': 'N,N-dimethylpropane- 1,3-diammonium iodide',
                     'NXRUEVJQMBGVAT-UHFFFAOYSA-N': 'N,N-Diethylpropane-1,3-diammonium iodide',
                     'N/A': 'None'}


features_sorted_by_importance = ['_feat_ASA-',
                                '_raw_v1-M_FCTHQYIDLRRROX-UHFFFAOYSA-N_final',
                                '_rxn_M_inorganic',
                                '_raw_reagent_1_volume',
                                '_raw_v1-M_BDAGIHXWWSANSR-UHFFFAOYSA-N_final',
                                '_rxn_M_acid',
                                '_raw_v1-M_RQQRAHKHDFPBMC-UHFFFAOYSA-L_final',
                                '_raw_reagent_2_volume',
                                '_raw_v1-M_ZEVRFFCPALTVDN-UHFFFAOYSA-N_final',
                                '_raw_v1-M_GGYGJCFIYJVWIP-UHFFFAOYSA-N_final',
                                '_raw_v1-M_QHJPGANWSLEMTI-UHFFFAOYSA-N_final',
                                '_raw_v1-M_YEJRWHAVMIAJKC-UHFFFAOYSA-N_final',
                                '_raw_reagent_2_v1-conc_YEJRWHAVMIAJKC-UHFFFAOYSA-N',
                                '_raw_reagent_0_volume',
                                '_raw_v1-M_XFYICZOIWSBQSK-UHFFFAOYSA-N_final',
                                '_raw_reagent_2_chemicals_0_actual_amount',
                                '_rxn_M_organic',
                                '_raw_reagent_6_volume',
                                '_raw_v1-M_UUDRLGYROXTISK-UHFFFAOYSA-N_final',
                                '_raw_reagent_5_chemicals_0_actual_amount',
                                '_raw_reagent_3_v1-conc_YEJRWHAVMIAJKC-UHFFFAOYSA-N',
                                '_raw_reagent_3_volume',
                                '_raw_reagent_4_volume',
                                '_raw_reagent_1_chemicals_2_actual_amount',
                                '_raw_v1-M_NOHLSFNWSBZSBW-UHFFFAOYSA-N_final',
                                '_raw_v1-M_JBOIAZWJIACNJF-UHFFFAOYSA-N_final',
                                '_raw_reagent_1_v1-conc_GGYGJCFIYJVWIP-UHFFFAOYSA-N',
                                '_raw_v1-M_LLWRXQXPJMPHLR-UHFFFAOYSA-N_final',
                                '_raw_reagent_6_chemicals_0_actual_amount',
                                '_raw_reagent_1_chemicals_0_actual_amount',
                                '_raw_reagent_1_chemicals_1_actual_amount',
                                '_raw_reagent_5_volume',
                                '_raw_reagent_2_chemicals_1_actual_amount',
                                '_raw_reagent_1_v1-conc_UUDRLGYROXTISK-UHFFFAOYSA-N',
                                '_feat_MinimalProjectionArea',
                                '_feat_msareaASAp',
                                '_raw_reagent_4_v1-conc_XFYICZOIWSBQSK-UHFFFAOYSA-N',
                                '_raw_v1-M_CQWGDVVCKBJLNX-UHFFFAOYSA-N_final',
                                '_raw_reagent_1_v1-conc_XFYICZOIWSBQSK-UHFFFAOYSA-N',
                                '_raw_v1-M_VNAAUNTYIONOHR-UHFFFAOYSA-N_final',
                                '_raw_reagent_1_v1-conc_YEJRWHAVMIAJKC-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_RQQRAHKHDFPBMC-UHFFFAOYSA-L',
                                '_raw_reagent_0_chemicals_0_actual_amount',
                                '_raw_reagent_3_v1-conc_XFYICZOIWSBQSK-UHFFFAOYSA-N',
                                '_feat_minimalprojectionsize',
                                '_raw_reagent_2_v1-conc_XFYICZOIWSBQSK-UHFFFAOYSA-N',
                                '_feat_molsurfaceareaVDWp',
                                '_feat_MaximalProjectionRadius',
                                '_feat_Refractivity',
                                '_raw_v1-M_NLJDBTZLVTWXRG-UHFFFAOYSA-N_final',
                                '_feat_VanderWaalsSurfaceArea',
                                '_feat_ASA_H',
                                '_raw_v1-M_KFQARYBEAKAXIC-UHFFFAOYSA-N_final',
                                '_feat_WienerIndex',
                                '_feat_BalabanIndex',
                                '_feat_ASA+',
                                '_feat_Accsitecount',
                                '_feat_ChainAtomCount',
                                '_feat_AtomCount_C',
                                '_raw_reagent_3_chemicals_2_actual_amount',
                                '_raw_reagent_3_chemicals_1_actual_amount',
                                '_feat_molsurfaceareaASAp',
                                '_feat_RotatableBondCount',
                                '_feat_msareaVDWp',
                                '_feat_LengthPerpendicularToTheMinArea',
                                '_feat_LengthPerpendicularToTheMaxArea',
                                '_feat_BondCount',
                                '_raw_molweight',
                                '_raw_reagent_1_v1-conc_CQWGDVVCKBJLNX-UHFFFAOYSA-N',
                                '_feat_ASA',
                                '_feat_AliphaticRingCount',
                                '_raw_reagent_3_v1-conc_GGYGJCFIYJVWIP-UHFFFAOYSA-N',
                                '_raw_reagent_3_chemicals_0_actual_amount',
                                '_feat_ASA_P',
                                '_feat_AvgPol',
                                '_raw_reagent_2_v1-conc_UUDRLGYROXTISK-UHFFFAOYSA-N',
                                '_raw_v1-M_ZMXDDKWLCZADIW-UHFFFAOYSA-N_final',
                                '_raw_reagent_3_v1-conc_RQQRAHKHDFPBMC-UHFFFAOYSA-L',
                                '_feat_Aliphati',
                                '_raw_reagent_2_v1-conc_CQWGDVVCKBJLNX-UHFFFAOYSA-N',
                                'tomCount',
                                '_raw_reagent_2_v1-conc_QHJPGANWSLEMTI-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_VMLAEGAAHIIWJX-UHFFFAOYSA-N',
                                '_raw_v1-M_QRFXELVDJSDWHX-UHFFFAOYSA-N_final',
                                '_raw_reagent_2_v1-conc_GGYGJCFIYJVWIP-UHFFFAOYSA-N',
                                '_raw_reagent_4_chemicals_1_actual_amount',
                                '_raw_reagent_1_v1-conc_QHJPGANWSLEMTI-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_FCTHQYIDLRRROX-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_VMLAEGAAHIIWJX-UHFFFAOYSA-N',
                                '_feat_MinimalProjectionRadius',
                                '_raw_reagent_1_v1-conc_KFQARYBEAKAXIC-UHFFFAOYSA-N',
                                '_feat_VanderWaalsVolume',
                                '_feat_fr_Imine',
                                '_raw_reagent_3_v1-conc_NOHLSFNWSBZSBW-UHFFFAOYSA-N',
                                '_raw_v1-M_VMLAEGAAHIIWJX-UHFFFAOYSA-N_final',
                                '_raw_reagent_6_v1-conc_BDAGIHXWWSANSR-UHFFFAOYSA-N',
                                '_feat_maximalprojectionsize',
                                '_raw_reagent_1_v1-conc_NOHLSFNWSBZSBW-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_QRFXELVDJSDWHX-UHFFFAOYSA-N',
                                '_raw_reagent_4_chemicals_0_actual_amount',
                                '_raw_reagent_2_v1-conc_CALQKRVFTWDYDG-UHFFFAOYSA-N',
                                '_raw_reagent_4_v1-conc_YEJRWHAVMIAJKC-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_FCTHQYIDLRRROX-UHFFFAOYSA-N',
                                '_feat_MaximalProjectionArea',
                                '_rxn_temperatureC_actual_bulk',
                                '_feat_HyperWienerIndex',
                                '_raw_reagent_2_v1-conc_NXRUEVJQMBGVAT-UHFFFAOYSA-N',
                                '_feat_ChiralCenterCount',
                                '_raw_reagent_4_v1-conc_ZMXDDKWLCZADIW-UHFFFAOYSA-N',
                                '_raw_v1-M_HBPSMMXRESDUSG-UHFFFAOYSA-N_final',
                                '_raw_reagent_2_v1-conc_GIAPQOZCVIEHNY-UHFFFAOYSA-N',
                                '_raw_v1-M_QZCGFUVVXNFSLE-UHFFFAOYSA-N_final',
                                '_raw_reagent_4_v1-conc_RQQRAHKHDFPBMC-UHFFFAOYSA-L',
                                '_raw_reagent_4_v1-conc_IAZDPXIOMUYVGZ-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_RYYSZNVPBLKLRS-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_JERSPYRKVMAEJY-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_QZCGFUVVXNFSLE-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_UMDDLGMCNFAZDX-UHFFFAOYSA-O',
                                '_raw_reagent_2_v1-conc_JBOIAZWJIACNJF-UHFFFAOYSA-N',
                                '_raw_reagent_5_chemicals_1_actual_amount',
                                '_raw_reagent_1_v1-conc_QRFXELVDJSDWHX-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_PXWSKGXEHZHFJA-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_JBOIAZWJIACNJF-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_VAWHFUNJDMQUSB-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_BJDYCCHRZIFCGN-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_DMFMZFFIQRMJQZ-UHFFFAOYSA-N',
                                '_raw_v1-M_PPCHYMCMRUGLHR-UHFFFAOYSA-N_final',
                                '_raw_reagent_0_chemicals_3_actual_amount',
                                '_raw_reagent_2_v1-conc_LCTUISCIGMWMAT-UHFFFAOYSA-N',
                                '_feat_acceptorcount',
                                '_feat_fr_pyridine',
                                '_raw_reagent_3_v1-conc_QRFXELVDJSDWHX-UHFFFAOYSA-N',
                                '_feat_fr_Ar_NH',
                                '_raw_reagent_3_v1-conc_ZMXDDKWLCZADIW-UHFFFAOYSA-N',
                                '_feat_MolPol',
                                '_raw_v1-M_WGYRINYTHSORGH-UHFFFAOYSA-N_final',
                                '_raw_reagent_2_v1-conc_FJFIJIDZQADKEE-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_HBPSMMXRESDUSG-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_IWNWLPUNKAYUAW-UHFFFAOYSA-N',
                                '_raw_v1-M_UXYJHTKQEFCXBJ-UHFFFAOYSA-N_final',
                                '_raw_reagent_1_v1-conc_LLWRXQXPJMPHLR-UHFFFAOYSA-N',
                                '_raw_reagent_6_chemicals_1_actual_amount',
                                '_raw_reagent_2_v1-conc_UVLZLKCGKYLKOR-UHFFFAOYSA-N',
                                '_raw_v1-M_LCTUISCIGMWMAT-UHFFFAOYSA-N_final',
                                '_feat_Protpsa',
                                '_feat_AromaticAtomCount',
                                '_raw_reagent_2_v1-conc_IAZDPXIOMUYVGZ-UHFFFAOYSA-N',
                                '_feat_HeteroaromaticRin',
                                '_feat_CarboaromaticRingCount',
                                '_raw_v1-M_UMDDLGMCNFAZDX-UHFFFAOYSA-O_final',
                                '_raw_reagent_1_v1-conc_VNAAUNTYIONOHR-UHFFFAOYSA-N',
                                '_raw_v1-M_JERSPYRKVMAEJY-UHFFFAOYSA-N_final',
                                '_feat_LargestRingSize',
                                '_rxn_stirrateRPM',
                                '_feat_HeteroaliphaticRingCount',
                                '_raw_reagent_1_v1-conc_IAZDPXIOMUYVGZ-UHFFFAOYSA-N',
                                '_raw_v1-M_YYMLRIWBISZOMT-UHFFFAOYSA-N_final',
                                '_raw_v1-M_PXWSKGXEHZHFJA-UHFFFAOYSA-N_final',
                                '_feat_Hacceptorcount',
                                '_raw_reagent_3_v1-conc_UMDDLGMCNFAZDX-UHFFFAOYSA-O',
                                '_raw_reagent_4_v1-conc_NOHLSFNWSBZSBW-UHFFFAOYSA-N',
                                '_raw_v1-M_FJFIJIDZQADKEE-UHFFFAOYSA-N_final',
                                '_raw_reagent_2_v1-conc_VAWHFUNJDMQUSB-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_VNAAUNTYIONOHR-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_SQXJHWOXNLTOOO-UHFFFAOYSA-N',
                                '_raw_reagent_4_v1-conc_UMDDLGMCNFAZDX-UHFFFAOYSA-O',
                                'ount',
                                '_raw_reagent_3_v1-conc_UPHCENSIMPJEIS-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_WGYRINYTHSORGH-UHFFFAOYSA-N',
                                '_feat_SmallestRingSize',
                                '_raw_reagent_1_v1-conc_YYMLRIWBISZOMT-UHFFFAOYSA-N',
                                '_raw_v1-M_NXRUEVJQMBGVAT-UHFFFAOYSA-N_final',
                                '_raw_reagent_2_v1-conc_XZUCBFLUEBDNSJ-UHFFFAOYSA-N',
                                '_feat_Hdonorcount',
                                '_raw_reagent_2_v1-conc_NOHLSFNWSBZSBW-UHFFFAOYSA-N',
                                '_raw_v1-M_QNNYEDWTOZODAS-UHFFFAOYSA-N_final',
                                '_raw_reagent_2_v1-conc_UPHCENSIMPJEIS-UHFFFAOYSA-N',
                                '_raw_v1-M_IWNWLPUNKAYUAW-UHFFFAOYSA-N_final',
                                '_raw_reagent_2_v1-conc_PBGZCCFVBVEIAS-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_BJDYCCHRZIFCGN-UHFFFAOYSA-N',
                                '_raw_v1-M_UPHCENSIMPJEIS-UHFFFAOYSA-N_final',
                                '_raw_reagent_2_chemicals_2_actual_amount',
                                '_raw_reagent_2_v1-conc_UMDDLGMCNFAZDX-UHFFFAOYSA-O',
                                '_rxn_reactiontimeS',
                                '_raw_reagent_2_v1-conc_PPCHYMCMRUGLHR-UHFFFAOYSA-N',
                                '_feat_fr_piperdine',
                                '_feat_PolarSurfaceArea',
                                '_feat_CarboaliphaticRingCount',
                                '_raw_reagent_5_v1-conc_BDAGIHXWWSANSR-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_NXRUEVJQMBGVAT-UHFFFAOYSA-N',
                                '_feat_fr_piperzine',
                                '_raw_reagent_6_chemicals_3_actual_amount',
                                '_feat_fr_NH0',
                                '_raw_reagent_1_v1-conc_HBZSVMFYMAOGRS-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_FJFIJIDZQADKEE-UHFFFAOYSA-N',
                                '_feat_fr_ArN',
                                '_raw_reagent_4_v1-conc_DMFMZFFIQRMJQZ-UHFFFAOYSA-N',
                                '_feat_AromaticRingCount',
                                '_raw_reagent_1_v1-conc_LCTUISCIGMWMAT-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_UVLZLKCGKYLKOR-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_SQXJHWOXNLTOOO-UHFFFAOYSA-N',
                                '_feat_fr_NH1',
                                '_raw_reagent_1_v1-conc_QNNYEDWTOZODAS-UHFFFAOYSA-N',
                                '_feat_donorcount',
                                '_feat_RingAtomCount',
                                '_raw_reagent_1_v1-conc_UZHWWTHDRVLCJU-UHFFFAOYSA-N',
                                '_raw_v1-M_RYYSZNVPBLKLRS-UHFFFAOYSA-N_final',
                                '_raw_reagent_1_v1-conc_NLJDBTZLVTWXRG-UHFFFAOYSA-N',
                                '_raw_reagent_4_v1-conc_GIAPQOZCVIEHNY-UHFFFAOYSA-N',
                                '_raw_reagent_3_v1-conc_DMFMZFFIQRMJQZ-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_QNNYEDWTOZODAS-UHFFFAOYSA-N',
                                '_feat_ProtPolarSurfaceArea',
                                '_raw_v1-M_VAWHFUNJDMQUSB-UHFFFAOYSA-N_final',
                                '_feat_fr_guanido',
                                '_raw_reagent_1_v1-conc_RYYSZNVPBLKLRS-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_UPHCENSIMPJEIS-UHFFFAOYSA-N',
                                '_feat_CarboRingCount',
                                '_raw_v1-M_UVLZLKCGKYLKOR-UHFFFAOYSA-N_final',
                                '_raw_reagent_3_v1-conc_CALQKRVFTWDYDG-UHFFFAOYSA-N',
                                '_raw_v1-M_HBZSVMFYMAOGRS-UHFFFAOYSA-N_final',
                                '_raw_reagent_2_v1-conc_KOAGKPNEVYEZDU-UHFFFAOYSA-N',
                                '_feat_CyclomaticNumber',
                                '_raw_v1-M_PBGZCCFVBVEIAS-UHFFFAOYSA-N_final',
                                '_raw_reagent_1_v1-conc_IWNWLPUNKAYUAW-UHFFFAOYSA-N',
                                '_raw_v1-M_KOAGKPNEVYEZDU-UHFFFAOYSA-N_final',
                                '_raw_v1-M_CALQKRVFTWDYDG-UHFFFAOYSA-N_final',
                                '_raw_reagent_3_chemicals_3_actual_amount',
                                '_raw_reagent_4_v1-conc_GGYGJCFIYJVWIP-UHFFFAOYSA-N',
                                '_rxn_mixingtime1S',
                                '_raw_reagent_3_v1-conc_IAZDPXIOMUYVGZ-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_null',
                                '_feat_WienerPolarity',
                                '_raw_reagent_2_v1-conc_UZHWWTHDRVLCJU-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_GIAPQOZCVIEHNY-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_BAMDIFIROXTEEM-UHFFFAOYSA-N',
                                '_raw_reagent_5_chemicals_2_actual_amount',
                                '_raw_reagent_1_v1-conc_CALQKRVFTWDYDG-UHFFFAOYSA-N',
                                '_feat_AtomCount_N',
                                '_raw_reagent_1_v1-conc_ZMXDDKWLCZADIW-UHFFFAOYSA-N',
                                '_raw_v1-M_BJDYCCHRZIFCGN-UHFFFAOYSA-N_final',
                                '_feat_donsitecount',
                                '_raw_reagent_4_chemicals_2_actual_amount',
                                '_raw_reagent_6_v1-conc_null',
                                '_feat_fr_dihydropyridine',
                                '_raw_reagent_2_v1-conc_null',
                                '_raw_reagent_1_v1-conc_ZEVRFFCPALTVDN-UHFFFAOYSA-N',
                                '_feat_fr_quatN',
                                '_raw_reagent_2_v1-conc_UXYJHTKQEFCXBJ-UHFFFAOYSA-N',
                                '_raw_reagent_6_chemicals_2_actual_amount',
                                '_raw_reagent_2_v1-conc_DMFMZFFIQRMJQZ-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_UXYJHTKQEFCXBJ-UHFFFAOYSA-N',
                                '_raw_reagent_4_chemicals_3_actual_amount',
                                '_raw_v1-M_JMXLWMIFDJCGBV-UHFFFAOYSA-N_final',
                                '_raw_reagent_0_chemicals_1_actual_amount',
                                '_raw_reagent_1_v1-conc_JERSPYRKVMAEJY-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_QZCGFUVVXNFSLE-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_KOAGKPNEVYEZDU-UHFFFAOYSA-N',
                                '_raw_reagent_3_v1-conc_null',
                                '_raw_v1-M_UZHWWTHDRVLCJU-UHFFFAOYSA-N_final',
                                '_raw_reagent_2_chemicals_3_actual_amount',
                                '_raw_reagent_5_chemicals_3_actual_amount',
                                '_raw_v1-M_null_final',
                                '_raw_reagent_3_v1-conc_PXWSKGXEHZHFJA-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_LLWRXQXPJMPHLR-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_WGYRINYTHSORGH-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_ZMXDDKWLCZADIW-UHFFFAOYSA-N',
                                '_raw_v1-M_BAMDIFIROXTEEM-UHFFFAOYSA-N_final',
                                '_raw_reagent_3_v1-conc_GIAPQOZCVIEHNY-UHFFFAOYSA-N',
                                '_raw_reagent_4_v1-conc_null',
                                '_raw_reagent_2_v1-conc_NLJDBTZLVTWXRG-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_PXWSKGXEHZHFJA-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_ZEVRFFCPALTVDN-UHFFFAOYSA-N',
                                '_raw_reagent_4_v1-conc_BDAGIHXWWSANSR-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_HBPSMMXRESDUSG-UHFFFAOYSA-N',
                                '_raw_reagent_4_v1-conc_PXWSKGXEHZHFJA-UHFFFAOYSA-N',
                                '_feat_fr_NH2',
                                '_raw_reagent_4_v1-conc_QRFXELVDJSDWHX-UHFFFAOYSA-N',
                                '_raw_reagent_4_v1-conc_CALQKRVFTWDYDG-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_JMXLWMIFDJCGBV-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_KFQARYBEAKAXIC-UHFFFAOYSA-N',
                                '_raw_reagent_0_chemicals_2_actual_amount',
                                '_raw_reagent_1_v1-conc_PBGZCCFVBVEIAS-UHFFFAOYSA-N',
                                '_raw_reagent_1_v1-conc_BAMDIFIROXTEEM-UHFFFAOYSA-N',
                                '_raw_v1-M_GIAPQOZCVIEHNY-UHFFFAOYSA-N_final',
                                '_feat_fr_amidine',
                                '_raw_v1-M_SQXJHWOXNLTOOO-UHFFFAOYSA-N_final',
                                '_raw_reagent_1_v1-conc_XZUCBFLUEBDNSJ-UHFFFAOYSA-N',
                                '_raw_reagent_1_chemicals_3_actual_amount',
                                '_raw_reagent_1_v1-conc_PPCHYMCMRUGLHR-UHFFFAOYSA-N',
                                '_raw_v1-M_IAZDPXIOMUYVGZ-UHFFFAOYSA-N_final',
                                '_rxn_mixingtime2S',
                                '_raw_reagent_2_v1-conc_YYMLRIWBISZOMT-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_RQQRAHKHDFPBMC-UHFFFAOYSA-L',
                                '_raw_v1-M_XZUCBFLUEBDNSJ-UHFFFAOYSA-N_final',
                                '_raw_reagent_2_v1-conc_HBZSVMFYMAOGRS-UHFFFAOYSA-N',
                                '_raw_reagent_2_v1-conc_JMXLWMIFDJCGBV-UHFFFAOYSA-N',
                                '_raw_reagent_5_v1-conc_null',
                                '_raw_v1-M_DMFMZFFIQRMJQZ-UHFFFAOYSA-N_final']
